[project]
name = "openai-proxy"
version = "0.1.0"
requires-python = ">=3.11"
readme = "READE.md"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi>=0.116.1",
    "openai>=1.98.0",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "uvicorn>=0.35.0",
]

